apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: payara-eks
  region: eu-central-1
  version: "1.17"

iam:
  withOIDC: true

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

# to enable CloudWatch logging
# cloudWatch:
#   clusterLogging:
#     enableTypes: ["*"]

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: default
        labels:
          scheduler: fargate
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
            
managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.large
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      # new feature for restricting SSH access to certain AWS security group IDs
      # sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
